osx_image: xcode7.3
language: objective-c
script:
  - |
    xcodebuild test \
    -project LTMorphingLabelDemo.xcodeproj \
    -scheme LTMorphingLabelDemo \
    -sdk iphonesimulator \
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'
